config/routes.rb
Yearbook::Application.routes.draw do

  get "buscar/index" 

  get "sessioncontroller/create"

  get "perfil/index"

  post "mural/index"

  devise_for :members

  resources :albums

  resources :usuarios

  root :to =>'home#index'
  match 'mural', controller: 'mural',action: 'index', via: 'get'

  devise_for :members,:controllers => { :registrations =>'registration'}
  match 'dashboard' => 'home#dashboard'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :descricao, :foto, :usuario_id
  belongs_to :usuario
end

app/models/contact.rb
class Contact < ActiveRecord::Base
belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base

devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :trackable, :validatable

validates :email, :foto, :descricao , :endereco, :username , :presence => true 

attr_accessible :email, :password, :password_confirmation, :foto, :descricao , :endereco , :remember_me, :username
has_one :contact
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :email, :nome, :senha
  has_one :album
  validates :nome, :email, :senha , :presence => true
  validates :email , :uniqueness => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	private
	  def stored_location_for(resource_or_scope)
  		nil
 	  end

	  def after_sign_in_path_for(resource_or_scope)
		@usuario = current_member
		id = @usuario.id
		'/perfil/index?id=' + id.to_s
  	  end
end

app/controllers/buscar_controller.rb
class BuscarController < ApplicationController
 
	def index
	  @membros = Member.search(params[:search])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

	def esperar
	end

	def logar
		email = params[:email]
		senha = senha[:senha]
		usuario = Usuario.where("senha = ? AND email = ?",senha,email)
		if !usuario.empty
			user = usuario[0]
			salvarUsuarioNaSessao(user)
			redirect_to "localhost:3000/mural"
		end
	end
end

app/controllers/mural_controller.rb
class MuralController < ApplicationController
	def index
		if params[:search] == nil
			@membros = Member.all
		  else
			@membros = Member.where('username like ?', "%"+params[:search]+"%")
			params[:search] = nil
		end
	end
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
  def index

  	@usuario = current_member
  	if (@usuario != nil)
  		@membro = Member.find(params[:id])
  	end



  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buscar_helper.rb
module BuscarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/mural_helper.rb
module MuralHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessioncontroller_helper.rb
module SessioncontrollerHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/buscar/index.html.erb
<% form_tag projects_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/home/dashboard.htmml.erb
<div class="painel2">
<p>hi welcome to Ruby community. you have successfully registered to your rails club account</p>
<%= link_to "Sign out", destroy_member_session_path, :method => :delete %>
</div>

app/views/home/index.html.erb
<div class="painel2">
	<% if member_signed_in? %>

		<h3>you have succesfully signed in</h3>
		<%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>

	<% else %>

		<h1> Bem vindo ao YearBook</h1>
			<p>Conecte-se a nosso Yearbook!<br/>
			    Basta se cadastrar e conhecer mais sobre a Disciplina de Tópicos em Computação<br/> e sobre os cursandos.
			</p>

	<% end %>
</div>

app/views/login/index.html.erb
<h1>Login</h1>

 <%= f.label :email %><br />
 <%= f.text_field :email %>

 <%= f.label :senha %><br />
 <%= f.password_field :senha %>

 <%= link_to 'Login',  action: 'Logar' %>

app/views/mural/index.html.erb
			<div class="logo2">
			  <%= form_tag :method => 'get' do %>
				  <%= text_field_tag :search, params[:search], :id => 'search_field' %>
				  <%= submit_tag "Buscar", :name => nil %> 
			  <% end %> 
			</div>	

		<div class="externa">	
			<h1 > Bem vindo ao YearBook!</h1>
			<p id="descricao">
				Este é o Yearbook da disciplina de Tópicos Especiais em Computação do curso de Ciência da Computação,
				oferecido pela Universidade Federal de Alfenas. <br />A disciplina dada à distância, e foi proposto o 
				desenvolvimento do yearbook em Ruby on Rails para os alunos desenvolverem. Aqui está nosso Yearbook! 
			</p>
			<div class="painelExterno">
				<% @membros.each do |membro| %>
					<div class="painel">				
							<h3><%= membro.username %></h3>
								<%= sanitize membro.descricao %>
							<%= link_to image_tag(membro.foto), {:controller => :perfil, :action => :index , :id => membro.id} %>
					</div>
				<% end %>
			</div>
		</div>
	

app/views/perfil/index.html.erb
<% if @usuario != nil %>
	<div class="painel2">
	
		<p><%=image_tag(@membro.foto) %></p>
		<h1><%= @membro.username %></h1>
			

		<p>Descrição: <%= @membro.descricao %></p>
		<p>Email: <%= @membro.email %></p>
		<p>Endereço: <%= @membro.endereco %></p>
	</div>
	<% else %>
		<%= render :text => "Você precisa estar logado para visualizar está página!" %>
<% end %>