config/routes.rb
Yearbook::Application.routes.draw do

  get "buscar/index" 

  get "sessioncontroller/create"

  get "perfil/index"

  post "mural/index"

  devise_for :members

  resources :albums

  resources :usuarios

  root :to =>'home#index'
  match 'mural', controller: 'mural',action: 'index', via: 'get'

  devise_for :members,:controllers => { :registrations =>'registration'}
  match 'dashboard' => 'home#dashboard'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :descricao, :foto, :usuario_id
  belongs_to :usuario
end

app/models/contact.rb
class Contact < ActiveRecord::Base
belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base

devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :trackable, :validatable

validates :email, :foto, :descricao , :endereco, :username , :presence => true 

attr_accessible :email, :password, :password_confirmation, :foto, :descricao , :endereco , :remember_me, :username
has_one :contact
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :email, :nome, :senha
  has_one :album
  validates :nome, :email, :senha , :presence => true
  validates :email , :uniqueness => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	private
	  def stored_location_for(resource_or_scope)
  		nil
 	  end

	  def after_sign_in_path_for(resource_or_scope)
		@usuario = current_member
		id = @usuario.id
		'/perfil/index?id=' + id.to_s
  	  end
end

app/controllers/buscar_controller.rb
class BuscarController < ApplicationController
 
	def index
	  @membros = Member.search(params[:search])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

	def esperar
	end

	def logar
		email = params[:email]
		senha = senha[:senha]
		usuario = Usuario.where("senha = ? AND email = ?",senha,email)
		if !usuario.empty
			user = usuario[0]
			salvarUsuarioNaSessao(user)
			redirect_to "localhost:3000/mural"
		end
	end
end

app/controllers/mural_controller.rb
class MuralController < ApplicationController
	def index
		if params[:search] == nil
			@membros = Member.all
		  else
			@membros = Member.where('username like ?', "%"+params[:search]+"%")
			params[:search] = nil
		end
	end
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
  def index

  	@usuario = current_member
  	if (@usuario != nil)
  		@membro = Member.find(params[:id])
  	end



  end
end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

def new

	@member= Member.new
	@contact = Contact.new
end

def create

	@member = Member.new
	@member.username = params[:member][:username]
	@member.email = params[:member][:email]
	@member.password = params[:member][:password]
	@member.password_confirmation =params[:member][:password_confirmation]
	@member.foto = params[:member][:foto]
	@member.endereco = params[:member][:endereco]
	@member.descricao = params[:member][:descricao]

	@contact = Contact.new
	@contact.mobile = params[:contact][:mobile]
	@contact.address = params[:contact][:address]
	@member.valid?
	if @member.errors.blank?

		@member.save
		@contact.member = @member
		@contact.save
		redirect_to dashboard_path
	else
		render :action => "new"
	end
end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buscar_helper.rb
module BuscarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/mural_helper.rb
module MuralHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessioncontroller_helper.rb
module SessioncontrollerHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario_id %><br />
    <%= f.number_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :foto %><br />
    <%= f.text_field :foto %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<div id = "albums_list">
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Foto</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr class ="listas">
    <td><%= album.usuario_id %></td>
    <td><%= album.foto %></td>
    <td><%= album.descricao %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @album.usuario_id %>
</p>

<p>
  <b>Foto:</b>
  <%= @album.foto %>
</p>

<p>
  <b>Descricao:</b>
  <%= @album.descricao %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.password_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table> 
  
    <th>Nome</th>
    <th>Email</th>
    <th>Senha</th>
    <th></th>
    <th></th>
    <th></th>

<% @usuarios.each do |usuario| %>
  <tr class ="listas">
    <td><%= usuario.nome %></td>
    <td><%= usuario.email %></td>
    <td><%= usuario.senha %></td>
    <td><%= link_to 'Show', usuario %></td>
    <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @usuario.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>

<p>
  <b>Senha:</b>
  <%= @usuario.senha %>
</p>


<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>